### PR TITLE
UTF-16 need to encode also new line

### PR DESCRIPTION
**Pull request by chapcz**

### CODE REVIEW

**Comment by f3l1x** [comment]
Thanks. :-) Could you please add some test?

**Comment by f3l1x** [comment]
ping @chapcz

**Comment by vody105** [comment]
@f3l1x ping, tests added

**Comment by paveljanda** [comment]
Hi, pls, can anyone explain me why the encoding conversion function was changed from iconv to mb_convert_encoding? It causes some problems, for example: https://github.com/contributte/datagrid/issues/956

**Comment by elring** [comment]
I probably see the reason. I tried to fix it back to use of iconv but tests now fail because iconv in UTF-16 apparently (sometimes) automatically include BOM, sometimes not. If you don't specify endianness (UTF-16), it includes BOM, if you do (UTF-16LE), it works. May be it is also dependent on host endianness...

I don't know the right solution. If we want to support property includeBom, we need sometimes strip the BOM, sometimes add it...

Or may be use simpler solution - use mb_convert_encoding for all encodings except for 'windows-1250', for which use iconv? Is it too ugly? :smiling_imp:

**Comment by paveljanda** [comment]
Haha, that would be a sneaky little workaround. It would not "fix" it in proper manner but it would solve most of current problems. 👍

**Comment by elring** [comment]
Okey :smile: PR #34

**Pull request merged**
